// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Harbor
{
    public static class GetProject
    {
        /// <summary>
        /// ## Example Usage
        /// 
        /// ```hcl
        /// data "harbor_project" "main" {
        ///     name    = "library" 
        /// }
        /// 
        /// output "project_id" {
        ///     value = data.harbor_project.main.id
        /// }
        /// ```
        /// </summary>
        public static Task<GetProjectResult> InvokeAsync(GetProjectArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetProjectResult>("harbor:index/getProject:getProject", args ?? new GetProjectArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```hcl
        /// data "harbor_project" "main" {
        ///     name    = "library" 
        /// }
        /// 
        /// output "project_id" {
        ///     value = data.harbor_project.main.id
        /// }
        /// ```
        /// </summary>
        public static Output<GetProjectResult> Invoke(GetProjectInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetProjectResult>("harbor:index/getProject:getProject", args ?? new GetProjectInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetProjectArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetProjectArgs()
        {
        }
        public static new GetProjectArgs Empty => new GetProjectArgs();
    }

    public sealed class GetProjectInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetProjectInvokeArgs()
        {
        }
        public static new GetProjectInvokeArgs Empty => new GetProjectInvokeArgs();
    }


    [OutputType]
    public sealed class GetProjectResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly int ProjectId;
        public readonly bool Public;
        public readonly bool VulnerabilityScanning;

        [OutputConstructor]
        private GetProjectResult(
            string id,

            string name,

            int projectId,

            bool @public,

            bool vulnerabilityScanning)
        {
            Id = id;
            Name = name;
            ProjectId = projectId;
            Public = @public;
            VulnerabilityScanning = vulnerabilityScanning;
        }
    }
}
