// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumiverse.harbor.InterrogationServicesArgs;
import com.pulumiverse.harbor.Utilities;
import com.pulumiverse.harbor.inputs.InterrogationServicesState;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.harbor.InterrogationServices;
 * import com.pulumi.harbor.InterrogationServicesArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var main = new InterrogationServices(&#34;main&#34;, InterrogationServicesArgs.builder()        
 *             .vulnerabilityScanPolicy(&#34;daily&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 */
@ResourceType(type="harbor:index/interrogationServices:InterrogationServices")
public class InterrogationServices extends com.pulumi.resources.CustomResource {
    /**
     * Sets the default interrogation service **Clair**
     * 
     */
    @Export(name="defaultScanner", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> defaultScanner;

    /**
     * @return Sets the default interrogation service **Clair**
     * 
     */
    public Output<Optional<String>> defaultScanner() {
        return Codegen.optional(this.defaultScanner);
    }
    /**
     * The frequency of the vulnerability scanning is done. This can be `daily`, `weekly`, `monthly` or can be a custom cron string.
     * 
     */
    @Export(name="vulnerabilityScanPolicy", refs={String.class}, tree="[0]")
    private Output<String> vulnerabilityScanPolicy;

    /**
     * @return The frequency of the vulnerability scanning is done. This can be `daily`, `weekly`, `monthly` or can be a custom cron string.
     * 
     */
    public Output<String> vulnerabilityScanPolicy() {
        return this.vulnerabilityScanPolicy;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public InterrogationServices(String name) {
        this(name, InterrogationServicesArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public InterrogationServices(String name, InterrogationServicesArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public InterrogationServices(String name, InterrogationServicesArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("harbor:index/interrogationServices:InterrogationServices", name, args == null ? InterrogationServicesArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private InterrogationServices(String name, Output<String> id, @Nullable InterrogationServicesState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("harbor:index/interrogationServices:InterrogationServices", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static InterrogationServices get(String name, Output<String> id, @Nullable InterrogationServicesState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new InterrogationServices(name, id, state, options);
    }
}
