// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumiverse.harbor.ProjectMemberGroupArgs;
import com.pulumiverse.harbor.Utilities;
import com.pulumiverse.harbor.inputs.ProjectMemberGroupState;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.harbor.Project;
 * import com.pulumi.harbor.ProjectMemberGroup;
 * import com.pulumi.harbor.ProjectMemberGroupArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var mainProject = new Project(&#34;mainProject&#34;);
 * 
 *         var mainProjectMemberGroup = new ProjectMemberGroup(&#34;mainProjectMemberGroup&#34;, ProjectMemberGroupArgs.builder()        
 *             .projectId(mainProject.id())
 *             .groupName(&#34;testing1&#34;)
 *             .role(&#34;projectadmin&#34;)
 *             .type(&#34;oidc&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * Harbor project member group can be imported using the `project id` and `member id` eg, `
 * 
 * ```sh
 *  $ pulumi import harbor:index/projectMemberGroup:ProjectMemberGroup main /projects/10/members/200
 * ```
 * 
 *  `
 * 
 */
@ResourceType(type="harbor:index/projectMemberGroup:ProjectMemberGroup")
public class ProjectMemberGroup extends com.pulumi.resources.CustomResource {
    @Export(name="groupId", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> groupId;

    public Output<Optional<Integer>> groupId() {
        return Codegen.optional(this.groupId);
    }
    @Export(name="groupName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> groupName;

    public Output<Optional<String>> groupName() {
        return Codegen.optional(this.groupName);
    }
    @Export(name="ldapGroupDn", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> ldapGroupDn;

    public Output<Optional<String>> ldapGroupDn() {
        return Codegen.optional(this.ldapGroupDn);
    }
    @Export(name="memberId", refs={Integer.class}, tree="[0]")
    private Output<Integer> memberId;

    public Output<Integer> memberId() {
        return this.memberId;
    }
    @Export(name="projectId", refs={String.class}, tree="[0]")
    private Output<String> projectId;

    public Output<String> projectId() {
        return this.projectId;
    }
    @Export(name="role", refs={String.class}, tree="[0]")
    private Output<String> role;

    public Output<String> role() {
        return this.role;
    }
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output<String> type;

    public Output<String> type() {
        return this.type;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ProjectMemberGroup(String name) {
        this(name, ProjectMemberGroupArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ProjectMemberGroup(String name, ProjectMemberGroupArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ProjectMemberGroup(String name, ProjectMemberGroupArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("harbor:index/projectMemberGroup:ProjectMemberGroup", name, args == null ? ProjectMemberGroupArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private ProjectMemberGroup(String name, Output<String> id, @Nullable ProjectMemberGroupState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("harbor:index/projectMemberGroup:ProjectMemberGroup", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ProjectMemberGroup get(String name, Output<String> id, @Nullable ProjectMemberGroupState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ProjectMemberGroup(name, id, state, options);
    }
}
