// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumiverse.harbor.RegistryArgs;
import com.pulumiverse.harbor.Utilities;
import com.pulumiverse.harbor.inputs.RegistryState;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.harbor.Registry;
 * import com.pulumi.harbor.RegistryArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var main = new Registry(&#34;main&#34;, RegistryArgs.builder()        
 *             .endpointUrl(&#34;https://hub.docker.com&#34;)
 *             .providerName(&#34;docker-hub&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * Harbor project can be imported using the `registry id` eg, `
 * 
 * ```sh
 *  $ pulumi import harbor:index/registry:Registry main /registries/7
 * ```
 * 
 *  `
 * 
 */
@ResourceType(type="harbor:index/registry:Registry")
public class Registry extends com.pulumi.resources.CustomResource {
    @Export(name="accessId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> accessId;

    public Output<Optional<String>> accessId() {
        return Codegen.optional(this.accessId);
    }
    @Export(name="accessSecret", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> accessSecret;

    public Output<Optional<String>> accessSecret() {
        return Codegen.optional(this.accessSecret);
    }
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    @Export(name="endpointUrl", refs={String.class}, tree="[0]")
    private Output<String> endpointUrl;

    public Output<String> endpointUrl() {
        return this.endpointUrl;
    }
    @Export(name="insecure", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> insecure;

    public Output<Optional<Boolean>> insecure() {
        return Codegen.optional(this.insecure);
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="providerName", refs={String.class}, tree="[0]")
    private Output<String> providerName;

    public Output<String> providerName() {
        return this.providerName;
    }
    @Export(name="registryId", refs={Integer.class}, tree="[0]")
    private Output<Integer> registryId;

    public Output<Integer> registryId() {
        return this.registryId;
    }
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    public Output<String> status() {
        return this.status;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Registry(String name) {
        this(name, RegistryArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Registry(String name, RegistryArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Registry(String name, RegistryArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("harbor:index/registry:Registry", name, args == null ? RegistryArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private Registry(String name, Output<String> id, @Nullable RegistryState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("harbor:index/registry:Registry", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "accessSecret"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Registry get(String name, Output<String> id, @Nullable RegistryState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Registry(name, id, state, options);
    }
}
