// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PurgeAuditLog extends pulumi.CustomResource {
    /**
     * Get an existing PurgeAuditLog resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PurgeAuditLogState, opts?: pulumi.CustomResourceOptions): PurgeAuditLog {
        return new PurgeAuditLog(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'harbor:index/purgeAuditLog:PurgeAuditLog';

    /**
     * Returns true if the given object is an instance of PurgeAuditLog.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PurgeAuditLog {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PurgeAuditLog.__pulumiType;
    }

    public readonly auditRetentionHour!: pulumi.Output<number>;
    public readonly includeOperations!: pulumi.Output<string>;
    public readonly schedule!: pulumi.Output<string>;

    /**
     * Create a PurgeAuditLog resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PurgeAuditLogArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PurgeAuditLogArgs | PurgeAuditLogState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PurgeAuditLogState | undefined;
            resourceInputs["auditRetentionHour"] = state ? state.auditRetentionHour : undefined;
            resourceInputs["includeOperations"] = state ? state.includeOperations : undefined;
            resourceInputs["schedule"] = state ? state.schedule : undefined;
        } else {
            const args = argsOrState as PurgeAuditLogArgs | undefined;
            if ((!args || args.auditRetentionHour === undefined) && !opts.urn) {
                throw new Error("Missing required property 'auditRetentionHour'");
            }
            if ((!args || args.includeOperations === undefined) && !opts.urn) {
                throw new Error("Missing required property 'includeOperations'");
            }
            if ((!args || args.schedule === undefined) && !opts.urn) {
                throw new Error("Missing required property 'schedule'");
            }
            resourceInputs["auditRetentionHour"] = args ? args.auditRetentionHour : undefined;
            resourceInputs["includeOperations"] = args ? args.includeOperations : undefined;
            resourceInputs["schedule"] = args ? args.schedule : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PurgeAuditLog.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PurgeAuditLog resources.
 */
export interface PurgeAuditLogState {
    auditRetentionHour?: pulumi.Input<number>;
    includeOperations?: pulumi.Input<string>;
    schedule?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PurgeAuditLog resource.
 */
export interface PurgeAuditLogArgs {
    auditRetentionHour: pulumi.Input<number>;
    includeOperations: pulumi.Input<string>;
    schedule: pulumi.Input<string>;
}
